version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  app:
      build: './'
      container_name: app
      restart: always
      ports:
        - "8080:8080"
      environment:
        DB_DSN: "host=postgres user=postgres password=postgres dbname=postgres port=5432"
volumes:
  db-data: